### ISSUE TITLE
Qt5 support

### ISSUE THREAD

**Issue by yarons** [Sirrix-AG/TPMManager#4]
Are there any plans to upgrade the Qt infra?

**Comment by kermitdafrog8** [comment]
Are you looking to compile under Qt5?

**Comment by kermitdafrog8** [comment]
I have patched it to compile under Qt5 5.15.3. I do not have any older computers with a TPM 1.x to test out the features to make sure that side works. But it compiles and loads without any issues.

**Comment by securitykernel** [comment]
Upgraded to Qt5 in #6.
